[build]
  publish = "web"
  
[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"

# Redirect root to the main graph page
[[redirects]]
  from = "/"
  to = "/graph.html"
  status = 200